apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-data
  namespace: logging
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: elastic-pv
