---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
     
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: elastic-disk
    fsType: ext4
